# Generated by Django 2.0.5 on 2018-09-24 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_userinfo_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='teachers',
            field=models.ManyToManyField(limit_choices_to={'depart__in': [1002, 1006]}, related_name='abc', to='crm.UserInfo', verbose_name='任课老师'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='consultant',
            field=models.ForeignKey(blank=True, limit_choices_to={'depart_id': 1001}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultanter', to='crm.UserInfo', verbose_name='课程顾问'),
        ),
    ]
